# Generated by Django 4.1.7 on 2023-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_category_character_dictionaryentry_language_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, unique=True),
        ),
    ]
