# Generated by Django 4.2.2 on 2023-06-14 18:48
"""
This migration loads the languagefamilies.json and languages.json fixtures.
First, it updates the Language and LanguageFamily schemas to allow null
created/last_modified dates. Then it loads the fixtures. Then it populates
the created/last_modified dates to the current time.
The schema are reverted to normal (no null dates) in the next migration.
"""

from django.core.management import call_command
from django.core.serializers import base, python
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def load_fixture(apps, schema_editor):
    old_get_model = python._get_model

    def _get_model(model_identifier):
        try:
            return apps.get_model(model_identifier)
        except (LookupError, TypeError):
            raise base.DeserializationError(
                "Invalid model identifier: '%s'" % model_identifier
            )

    python._get_model = _get_model

    try:
        call_command("loaddata", "language_families.json", app_label="backend")
        call_command("loaddata", "languages.json", app_label="backend")
    finally:
        python._get_model = old_get_model


def populate_dates(apps, schema_editor):
    languagefamilies = apps.get_model("backend", "languagefamily")
    for item in languagefamilies.objects.filter(
        Q(created=None) | Q(last_modified=None)
    ):
        item.created = timezone.now()
        item.last_modified = timezone.now()
        item.save()

    languages = apps.get_model("backend", "language")
    for item in languages.objects.filter(Q(created=None) | Q(last_modified=None)):
        item.created = timezone.now()
        item.last_modified = timezone.now()
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_load_initial_data_fixtures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagefamily",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="languagefamily",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        # the following operations are irreversible!
        # to unapply this migration, delete the loaded data from your db, then comment out the next two lines.
        # then you can unapply the migration.
        migrations.RunPython(load_fixture),
        migrations.RunPython(populate_dates),
    ]
