# Generated by Django 4.1.7 on 2023-04-24 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_alphabet_dictionaryentryrelatedcharacter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dictionaryentry",
            old_name="categories",
            new_name="category",
        ),
        migrations.AddField(
            model_name="dictionaryentrylink",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="dictionaryentryrelatedcharacter",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
