# Generated by Django 4.1.7 on 2023-04-27 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_rename_uuid_dictionaryentrylink_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("site", "title")},
        ),
    ]
