# Generated by Django 4.1.7 on 2023-04-27 18:36
# This migration sets the null values back to false on the created and
# last_modified fields for the AppJson and PartsOfSpeech models after the
# fixtures have been loaded in the previous migration.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_auto_20230427_1134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appjson",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="appjson",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="partofspeech",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="partofspeech",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
