# Generated by Django 4.1.7 on 2023-04-28 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dictionaryentrylink",
            options={
                "verbose_name": "related dictionary entry",
                "verbose_name_plural": "related dictionary entries",
            },
        ),
        migrations.AlterModelOptions(
            name="dictionaryentryrelatedcharacter",
            options={
                "verbose_name": "character - dictionary entry relation",
                "verbose_name_plural": "character - dictionary entry relations",
            },
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="category",
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="related_characters",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_dictionary_entries",
                through="backend.DictionaryEntryRelatedCharacter",
                to="backend.character",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentrylink",
            name="from_dictionary_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dictionaryentrylink_set",
                to="backend.dictionaryentry",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentrylink",
            name="to_dictionary_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_dictionaryentrylink_set",
                to="backend.dictionaryentry",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentryrelatedcharacter",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.character",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentryrelatedcharacter",
            name="dictionary_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.dictionaryentry",
            ),
        ),
        migrations.CreateModel(
            name="DictionaryEntryCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_trashed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictionaryentrycategory_set",
                        to="backend.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dictionary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictionaryentrycategory_set",
                        to="backend.dictionaryentry",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "category - dictionary entry relation",
                "verbose_name_plural": "category - dictionary entry relations",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="dictionary_entries",
                through="backend.DictionaryEntryCategory",
                to="backend.category",
            ),
        ),
    ]
