# Generated by Django 4.1.7 on 2023-05-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_alter_dictionaryentrylink_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="wotd_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="wotd_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
