# Generated by Django 4.1.7 on 2023-05-01 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_alter_dictionaryentrylink_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alphabet",
            options={"verbose_name": "alphabet", "verbose_name_plural": "alphabet"},
        ),
    ]
