# Generated by Django 4.1.7 on 2023-05-08 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_dictionaryentry_exclude_from_wotd_wordoftheday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="dictionaryentry",
            options={
                "ordering": ["title"],
                "verbose_name": "Dictionary Entry",
                "verbose_name_plural": "Dictionary Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="partofspeech",
            options={
                "ordering": ["title"],
                "verbose_name": "Part Of Speech",
                "verbose_name_plural": "Parts Of Speech",
            },
        ),
        migrations.AlterModelOptions(
            name="wordoftheday",
            options={
                "ordering": ["-date"],
                "verbose_name": "Word of the day",
                "verbose_name_plural": "Words of the day",
            },
        ),
    ]
