# Generated by Django 4.2.1 on 2023-05-09 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0019_alter_category_options_alter_dictionaryentry_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
