# Generated by Django 4.2.1 on 2023-05-15 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0019_alter_category_options_alter_dictionaryentry_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="notes",
            new_name="note",
        ),
    ]
