# Generated by Django 4.2.1 on 2023-05-16 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_customorderrecalculationpreviewresult"),
        ("backend", "0020_rename_notes_character_note"),
    ]

    operations = []
