# Generated by Django 4.2.1 on 2023-05-16 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_rename_notes_character_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acknowledgement",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="alphabet",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="alternatespelling",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="appjson",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="appmembership",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="character",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="charactervariant",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="dictionaryentrycategory",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="dictionaryentrylink",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="dictionaryentryrelatedcharacter",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="ignoredcharacter",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="language",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="languagefamily",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="note",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="partofspeech",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="pronunciation",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="site",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="sitefeature",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="sitemenu",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="wordoftheday",
            name="is_trashed",
        ),
    ]
