# Generated by Django 4.2.1 on 2023-05-17 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_merge_20230516_0952"),
        ("backend", "0021_remove_acknowledgement_is_trashed_and_more"),
    ]

    operations = []
