# Generated by Django 4.2.1 on 2023-05-18 21:33

import backend.models.media
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="content",
            field=models.ImageField(upload_to=backend.models.media.user_directory_path),
        ),
    ]
