# Generated by Django 4.2.1 on 2023-05-17 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_merge_20230517_1354"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customorderrecalculationpreviewresult",
            name="is_trashed",
        ),
    ]
