# Generated by Django 4.2.1 on 2023-05-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_audio_video_person_image_audiospeaker_audio_speakers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="file",
        ),
        migrations.RemoveField(
            model_name="image",
            name="file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="file",
        ),
        migrations.AlterField(
            model_name="audio",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="audio",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="image",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="video",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
