# Generated by Django 4.2.1 on 2023-05-24 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_audio_alter_image_options_image_acknowledgement_and_more"),
        ("backend", "0023_remove_customorderrecalculationpreviewresult_is_trashed"),
    ]

    operations = []
