# Generated by Django 4.2.1 on 2023-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_audio_alter_image_options_image_acknowledgement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="related_audio",
            field=models.ManyToManyField(to="backend.audio"),
        ),
        migrations.AddField(
            model_name="character",
            name="related_images",
            field=models.ManyToManyField(to="backend.image"),
        ),
        migrations.AddField(
            model_name="character",
            name="related_videos",
            field=models.ManyToManyField(to="backend.video"),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="related_audio",
            field=models.ManyToManyField(to="backend.audio"),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="related_images",
            field=models.ManyToManyField(to="backend.image"),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="related_videos",
            field=models.ManyToManyField(to="backend.video"),
        ),
        migrations.AlterField(
            model_name="audio",
            name="speakers",
            field=models.ManyToManyField(
                related_name="audio_set",
                through="backend.AudioSpeaker",
                to="backend.person",
            ),
        ),
    ]
