# Generated by Django 4.2.1 on 2023-05-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_character_related_audio_character_related_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                related_name="audio_set",
                through="backend.AudioSpeaker",
                to="backend.person",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="related_audio",
            field=models.ManyToManyField(blank=True, to="backend.audio"),
        ),
        migrations.AlterField(
            model_name="character",
            name="related_images",
            field=models.ManyToManyField(blank=True, to="backend.image"),
        ),
        migrations.AlterField(
            model_name="character",
            name="related_videos",
            field=models.ManyToManyField(blank=True, to="backend.video"),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="related_audio",
            field=models.ManyToManyField(blank=True, to="backend.audio"),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="related_images",
            field=models.ManyToManyField(blank=True, to="backend.image"),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="related_videos",
            field=models.ManyToManyField(blank=True, to="backend.video"),
        ),
    ]
