# Generated by Django 4.2.1 on 2023-05-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_merge_20230525_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="customorderrecalculationpreviewresult",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
