# Generated by Django 4.2.1 on 2023-05-26 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0025_alter_audio_speakers_alter_character_related_audio_and_more"),
        (
            "backend",
            "0026_rename_date_customorderrecalculationpreviewresult_latest_recalculation_date_and_more",
        ),
    ]

    operations = []
