# Generated by Django 4.2.1 on 2023-06-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("backend", "0027_merge_20230525_1714"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="banner_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_banner_of",
                to="backend.image",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="banner_video",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_banner_of",
                to="backend.video",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="logo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_logo_of",
                to="backend.image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("banner_image__isnull", True),
                    ("banner_video__isnull", True),
                    _connector="OR",
                ),
                name="only_one_banner",
            ),
        ),
    ]
