# Generated by Django 4.2.1 on 2023-06-01 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_customorderrecalculationresult_and_more"),
        ("backend", "0028_user_groups"),
    ]

    operations = []
