# Generated by Django 4.2.1 on 2023-06-01 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="banner_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_banner_of",
                to="backend.image",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="banner_video",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_banner_of",
                to="backend.video",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="logo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_logo_of",
                to="backend.image",
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("banner_image__isnull", True),
                    ("banner_video__isnull", True),
                    _connector="OR",
                ),
                name="only_one_banner",
            ),
        ),
    ]
