# Generated by Django 4.2.1 on 2023-06-02 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_merge_20230601_1550"),
        ("backend", "0029_site_banner_image_site_banner_video_site_logo_and_more"),
    ]

    operations = []
