# Generated by Django 4.2.1 on 2023-06-02 21:02

import backend.models.media
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_site_banner_image_site_banner_video_site_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="medium",
            field=models.ImageField(
                blank=True, upload_to=backend.models.media.media_directory_path
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="small",
            field=models.ImageField(
                blank=True, upload_to=backend.models.media.media_directory_path
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to=backend.models.media.media_directory_path
            ),
        ),
    ]
