# Generated by Django 4.2.1 on 2023-06-05 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0030_image_medium_image_small_image_thumbnail"),
        ("backend", "0030_merge_20230602_1521"),
    ]

    operations = []
