# Generated by Django 4.2.2 on 2023-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0033_remove_audio_content_remove_image_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
