# Generated by Django 4.2.2 on 2023-06-14 19:16
"""
This migration sets the Language and LanguageFamily schemas back to normal after 
allowing null created/last_modified dates in the last migration when loading.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0034_load_languagefamily_language_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagefamily",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="languagefamily",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
