# Generated by Django 4.2.2 on 2023-06-14 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0034_remove_audio_content_remove_image_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="medium_id",
            new_name="medium",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="small_id",
            new_name="small",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="thumbnail_id",
            new_name="thumbnail",
        ),
    ]
