# Generated by Django 4.2.2 on 2023-06-14 19:09

import backend.models.sites
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0035_rename_medium_id_image_medium_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="languagefamily",
            managers=[
                ("objects", backend.models.sites.LanguageFamilyManager()),
            ],
        ),
    ]
