# Generated by Django 4.2.2 on 2023-06-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0038_reset_languagefamily_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="medium",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_medium",
                to="backend.imagefile",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="small",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_small",
                to="backend.imagefile",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_thumbnail",
                to="backend.imagefile",
            ),
        ),
    ]
