# Generated by Django 4.2.2 on 2023-06-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0039_video_medium_video_small_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="medium",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_medium",
                to="backend.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="small",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_small",
                to="backend.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail",
                to="backend.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="medium",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_medium",
                to="backend.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="small",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_small",
                to="backend.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_thumbnail",
                to="backend.imagefile",
            ),
        ),
    ]
