# Generated by Django 4.2.2 on 2023-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0045_remove_user_is_superuser_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
