# Generated by Django 4.2.3 on 2023-07-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0046_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitewidgetlist",
            name="widgets",
            field=models.ManyToManyField(
                related_name="sitewidgetlist_set",
                through="backend.SiteWidgetListOrder",
                to="backend.sitewidget",
            ),
        ),
    ]
