# Generated by Django 4.2.2 on 2023-07-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0046_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="cover_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="song_cover_of",
                to="backend.image",
            ),
        ),
    ]
