# Generated by Django 4.2.3 on 2023-07-13 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_song_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translation",
            name="language",
        ),
    ]
