# Generated by Django 4.2.2 on 2023-07-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0047_alter_song_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagefile",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videofile",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
