# Generated by Django 4.2.3 on 2023-07-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0047_alter_sitewidgetlist_widgets"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sitewidgetlistorder",
            name="unique_widget_order",
        ),
        migrations.AddField(
            model_name="sitewidgetlistorder",
            name="site",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="backend.site",
            ),
        ),
        migrations.AddField(
            model_name="sitewidgetlistorder",
            name="visibility",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                editable=False,
                null=True,
            ),
        ),
    ]
