# Generated by Django 4.2.3 on 2023-07-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0048_file_size_imagefile_size_videofile_size"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sitewidgetlistorder",
            name="unique_widget_order",
        ),
        migrations.AlterField(
            model_name="sitewidgetlist",
            name="widgets",
            field=models.ManyToManyField(
                related_name="sitewidgetlist_set",
                through="backend.SiteWidgetListOrder",
                to="backend.sitewidget",
            ),
        ),
    ]
