# Generated by Django 4.2.3 on 2023-07-13 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0048_remove_translation_language"),
        ("backend", "0049_remove_sitewidgetlistorder_unique_widget_order_and_more"),
    ]

    operations = []
