# Generated by Django 4.2.2 on 2023-07-14 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0050_merge_20230713_1142"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiospeaker",
            name="site",
        ),
    ]
