# Generated by Django 4.2.2 on 2023-07-24 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0053_story_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiospeaker",
            name="site",
        ),
    ]
