# Generated by Django 4.2.3 on 2023-07-24 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0054_remove_audiospeaker_site"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sitewidgetlistorder",
            unique_together={("site_widget", "site_widget_list")},
        ),
    ]
