# Generated by Django 4.2.2 on 2023-07-25 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0055_alter_sitewidgetlistorder_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Page",
            new_name="StoryPage",
        ),
        migrations.AlterModelOptions(
            name="storypage",
            options={
                "ordering": ("ordering",),
                "verbose_name": "story page",
                "verbose_name_plural": "story pages",
            },
        ),
        migrations.AlterUniqueTogether(
            name="story",
            unique_together=set(),
        ),
    ]
