# Generated by Django 4.2.3 on 2023-07-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0055_alter_sitewidgetlistorder_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitepage",
            name="widgets",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sitepage_set",
                to="backend.sitewidgetlist",
            ),
        ),
    ]
