# Generated by Django 4.2.2 on 2023-07-25 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0056_rename_page_storypage_alter_storypage_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="song",
            unique_together=set(),
        ),
    ]
