# Generated by Django 4.2.2 on 2023-07-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0057_alter_song_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="storypage",
            name="site",
            field=models.ForeignKey(
                default="9637d460-b150-4a16-b480-54592ab8a89a",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="backend.site",
            ),
            preserve_default=False,
        ),
    ]
