# Generated by Django 4.2.3 on 2023-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0059_storypage_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
    ]
