# Generated by Django 4.2.4 on 2023-08-14 17:05

import backend.models.media
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0061_remove_song_cover_image_remove_story_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(
                max_length=500, upload_to=backend.models.files.file_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="content",
            field=models.ImageField(
                height_field="height",
                max_length=500,
                upload_to=backend.models.files.file_directory_path,
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="content",
            field=models.FileField(
                max_length=500, upload_to=backend.models.files.file_directory_path
            ),
        ),
    ]
