# Generated by Django 4.2.4 on 2023-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0062_alter_file_content_alter_imagefile_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widgetsettings",
            name="value",
            field=models.TextField(blank=True),
        ),
    ]
