# Generated by Django 4.2.4 on 2023-08-16 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0063_alter_widgetsettings_value"),
        ("backend", "0063_remove_translation_part_of_speech_and_more"),
    ]

    operations = []
