# Generated by Django 4.2.4 on 2023-08-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0064_merge_20230816_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="format",
            field=models.IntegerField(
                choices=[
                    (0, "Default"),
                    (1, "Left"),
                    (2, "Right"),
                    (3, "Full"),
                    (4, "Center"),
                ],
                default=0,
            ),
        ),
    ]
