# Generated by Django 4.2.4 on 2023-09-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0068_alter_acknowledgement_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitepage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
