# Generated by Django 4.2.4 on 2023-09-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0069_alter_song_acknowledgements_alter_song_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lyric",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="lyric",
            name="translation",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="introduction_translation",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="introduction_translation",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="storypage",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="storypage",
            name="translation",
            field=models.TextField(blank=True),
        ),
    ]
