# Generated by Django 4.2.5 on 2023-09-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0070_alter_lyric_text_alter_lyric_translation_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["site", "title"], name="category_site_title_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["site", "title"], name="character_title_idx"),
        ),
        migrations.AddIndex(
            model_name="charactervariant",
            index=models.Index(fields=["site", "title"], name="cv_site_title_idx"),
        ),
        migrations.AddIndex(
            model_name="customorderrecalculationresult",
            index=models.Index(
                fields=["site", "is_preview"], name="corr_site_preview_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dictionaryentry",
            index=models.Index(
                fields=["site", "type", "visibility", "exclude_from_wotd"],
                name="dictionary_wotd_candidates_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ignoredcharacter",
            index=models.Index(
                fields=["site", "title"], name="ignoredcharacter_title_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitefeature",
            index=models.Index(fields=["site", "key"], name="sitefeature_key_idx"),
        ),
        migrations.AddIndex(
            model_name="sitepage",
            index=models.Index(fields=["slug", "site"], name="page_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="wordoftheday",
            index=models.Index(fields=["date", "site"], name="wotd_date_idx"),
        ),
    ]
