# Generated by Django 4.2.5 on 2023-09-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0071_category_category_site_title_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="category_site_title_idx",
        ),
        migrations.RemoveIndex(
            model_name="character",
            name="character_title_idx",
        ),
        migrations.RemoveIndex(
            model_name="charactervariant",
            name="cv_site_title_idx",
        ),
        migrations.RemoveIndex(
            model_name="ignoredcharacter",
            name="ignoredcharacter_title_idx",
        ),
        migrations.RemoveIndex(
            model_name="sitefeature",
            name="sitefeature_key_idx",
        ),
        migrations.RemoveIndex(
            model_name="wordoftheday",
            name="wotd_date_idx",
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["title", "site"], name="category_site_title_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["title", "site"], name="character_title_idx"),
        ),
        migrations.AddIndex(
            model_name="charactervariant",
            index=models.Index(fields=["title", "site"], name="cv_site_title_idx"),
        ),
        migrations.AddIndex(
            model_name="ignoredcharacter",
            index=models.Index(
                fields=["title", "site"], name="ignoredcharacter_title_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitefeature",
            index=models.Index(fields=["key", "site"], name="sitefeature_key_idx"),
        ),
        migrations.AddIndex(
            model_name="wordoftheday",
            index=models.Index(fields=["site", "date"], name="wotd_date_idx"),
        ),
    ]
