# Generated by Django 4.2.5 on 2023-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0073_alter_person_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionaryentry",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sitepage",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sitewidget",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="storypage",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                db_index=True,
                default=0,
            ),
        ),
    ]
