# Generated by Django 4.2.5 on 2023-10-05 21:04

import backend.permissions.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0075_alter_imagefile_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-30, "Cancelled"),
                            (-20, "Rejected"),
                            (-10, "Ignored"),
                            (0, "Pending"),
                            (10, "Approved"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "reason",
                    models.IntegerField(
                        choices=[
                            (0, "Other"),
                            (10, "Learning the language"),
                            (20, "Teaching the language"),
                            (30, "Fluent speaker"),
                            (40, "Interested in languages"),
                            (50, "Part of my heritage"),
                            (60, "Member of this community/nation"),
                            (70, "Working with this community/nation"),
                            (80, "Reconciliation"),
                            (90, "Part of this FirstVoices Language Team"),
                        ],
                        default=0,
                    ),
                ),
                ("reason_note", models.CharField(max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="backend.site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Join Request",
                "verbose_name_plural": "Join Requests",
                "indexes": [
                    models.Index(
                        fields=["site", "status"], name="join_request_status_idx"
                    )
                ],
            },
            bases=(
                backend.permissions.managers.PermissionFilterMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="joinrequest",
            constraint=models.UniqueConstraint(
                fields=("site", "user"), name="unique_site_user_join_request"
            ),
        ),
    ]
