# Generated by Django 4.2.6 on 2023-10-10 21:40

from django.conf import settings
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


def move_contact_email(apps, schema_editor):
    Site = apps.get_model("backend", "Site")
    for site in Site.objects.all():
        if site.contact_email_old:
            site.contact_email = [site.contact_email_old]
        site.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0076_joinrequest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="contact_email",
            new_name="contact_email_old",
        ),
        migrations.AddField(
            model_name="site",
            name="contact_email",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="contact_users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(move_contact_email),
    ]
