# Generated by Django 4.2.5 on 2023-10-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0076_joinrequest"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="joinrequest",
            constraint=models.UniqueConstraint(
                fields=("site", "user"), name="unique_site_user_join_request"
            ),
        ),
    ]
