# Generated by Django 4.2.6 on 2023-10-17 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0077_site_contact_email_site_contact_us_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="contact_email",
            new_name="contact_emails",
        ),
    ]
