# Generated by Django 4.2.5 on 2023-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0077_joinrequest_unique_site_user_join_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (-20, "Cancelled"),
                    (-10, "Rejected"),
                    (0, "Pending"),
                    (10, "Approved"),
                ],
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="joinrequest",
            index=models.Index(
                fields=["site", "status"], name="join_request_status_idx"
            ),
        ),
    ]
