# Generated by Django 4.2.6 on 2023-10-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0079_remove_joinrequest_reason_joinrequestreason"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="joinrequestreason",
            constraint=models.UniqueConstraint(
                fields=("join_request", "reason"),
                name="unique_reasons_per_join_request",
            ),
        ),
    ]
