# Generated by Django 4.2.6 on 2023-11-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0080_joinrequestreason_unique_reasons_per_join_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="reason_note",
            field=models.CharField(max_length=2500),
        ),
    ]
