# Generated by Django 4.2.7 on 2023-11-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0082_immersionlabel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immersionlabel",
            name="dictionary_entry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="immersion_labels",
                to="backend.dictionaryentry",
            ),
        ),
    ]
