# Generated by Django 4.2.7 on 2023-11-30 23:01

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0082_immersionlabel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="split_chars_base",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
