# Generated by Django 4.2.6 on 2023-12-04 22:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0083_dictionaryentry_split_chars_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="community_keywords",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name="language",
            name="alternate_names",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name="language",
            name="title",
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name="languagefamily",
            name="alternate_names",
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name="languagefamily",
            name="title",
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                max_length=225,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="title",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
