# Generated by Django 4.2.7 on 2023-12-07 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0085_gallery_galleryimage_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GalleryImage",
            new_name="GalleryItem",
        ),
    ]
