# Generated by Django 4.2.7 on 2023-12-07 22:42

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0085_gallery_galleryitem_galleryitem_unique_gallery_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="immersionlabel",
            name="key",
            field=models.SlugField(
                max_length=225,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitefeature",
            name="key",
            field=models.SlugField(
                max_length=225,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
