# Generated by Django 4.2.7 on 2023-12-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0086_alter_immersionlabel_key_alter_sitefeature_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="immersionlabel",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Team"), (10, "Members"), (20, "Public")],
                db_index=True,
                default=0,
            ),
        ),
    ]
