# Generated by Django 4.2.7 on 2023-12-12 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0086_alter_immersionlabel_key_alter_sitefeature_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleryitem_set",
                to="backend.gallery",
            ),
        ),
    ]
