# Generated by Django 4.2.7 on 2023-12-15 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0087_immersionlabel_visibility"),
        ("backend", "0087_mtdexportformat"),
    ]

    operations = []
