# Generated by Django 4.2.7 on 2023-12-18 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0087_alter_galleryitem_gallery"),
        ("backend", "0088_mtdexportformat"),
    ]

    operations = []
