# Generated by Django 4.2.7 on 2024-01-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0089_merge_20231218_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_cover_image",
                to="backend.image",
            ),
        ),
    ]
