# Generated by Django 4.2.7 on 2024-01-08 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0090_alter_gallery_cover_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmbeddedVideo",
        ),
    ]
