# Generated by Django 4.2.7 on 2024-01-22 20:37

from django.db import migrations


def update_appjson_defaults(apps, schema_editor):
    AppJson = apps.get_model('backend', 'AppJson')

    # Fetch the existing record with the key 'default_site_menu'
    appjson = AppJson.objects.get(key='default_site_menu')

    # Update the json field with the new data
    appjson.json = {
        "kids": {
            "id": "kids",
            "href": "/kids",
            "title": "Kids",
            "transKey": "navigation-kids",
            "itemsData": []
        },
        "about": {
            "id": "about",
            "title": "About",
            "transKey": "navigation-about",
            "itemsData": [{
                "href": "/our-language",
                "title": "Our Language",
                "transKey": "navigation-our-language"
            }, {
                "href": "/our-people",
                "title": "Our People",
                "transKey": "navigation-our-people"
            }]
        },
        "learn": {
            "id": "learn",
            "title": "Learn",
            "transKey": "navigation-learn",
            "itemsData": [{
                "href": "/songs",
                "title": "Songs",
                "transKey": "navigation-songs"
            }, {
                "href": "/stories",
                "title": "Stories",
                "transKey": "navigation-stories"
            }, {
                "href": "/games",
                "title": "Games",
                "transKey": "navigation-games"
            }]
        },
        "resources": {
            "id": "resources",
            "title": "Resources",
            "transKey": "navigation-resources",
            "itemsData": [{
                "href": "/keyboards",
                "title": "Keyboards",
                "transKey": "navigation-keyboards"
            }]
        },
        "dictionary": {
            "id": "dictionary",
            "title": "Dictionary",
            "transKey": "navigation-dictionary",
            "itemsData": [{
                "href": "/words",
                "title": "Words",
                "transKey": "navigation-words"
            }, {
                "href": "/phrases",
                "title": "Phrases",
                "transKey": "navigation-phrases"
            }, {
                "href": "/alphabet",
                "title": "Alphabet",
                "transKey": "navigation-alphabet"
            }, {
                "href": "/categories",
                "title": "Categories",
                "transKey": "navigation-categories"
            }]
        }
    }

    # Save the updated record
    appjson.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0092_character_related_video_links_and_more"),
    ]

    operations = [
        migrations.RunPython(update_appjson_defaults),
    ]
