# Generated by Django 4.2.7 on 2024-01-23 21:49

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0094_alter_immersionlabel_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitefeature",
            name="key",
            field=models.SlugField(
                max_length=225,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
