# Generated by Django 4.2.7 on 2024-01-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0096_remove_audio_is_shared_remove_image_is_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
