# Generated by Django 4.2.7 on 2024-02-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0097_site_is_hidden"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="galleryitem",
            name="unique_gallery_item_order",
        ),
        migrations.RemoveIndex(
            model_name="galleryitem",
            name="gallery_item_order_idx",
        ),
        migrations.RenameField(
            model_name="galleryitem",
            old_name="order",
            new_name="ordering",
        ),
        migrations.AddIndex(
            model_name="galleryitem",
            index=models.Index(
                fields=["gallery", "ordering"], name="gallery_item_ordering_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="galleryitem",
            constraint=models.UniqueConstraint(
                fields=("gallery", "ordering"), name="unique_gallery_item_order"
            ),
        ),
    ]
