# Generated by Django 4.2.7 on 2024-03-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0098_remove_galleryitem_unique_gallery_item_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="community_keywords",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
