# Generated by Django 4.2.7 on 2024-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0099_alter_language_community_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="community_keywords",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
