# Generated by Django 4.2.7 on 2024-04-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0102_importjobreport_importjobreportrow_importjob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importjobreport",
            options={
                "verbose_name": "Import Job Report",
                "verbose_name_plural": "Import Job Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="importjobreportrow",
            options={
                "verbose_name": "Import Job Report Row",
                "verbose_name_plural": "Import Job Report Rows",
            },
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="title",
        ),
        migrations.AddField(
            model_name="importjob",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
