# Generated by Django 4.2.7 on 2024-05-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0104_alter_mtdexportformat_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importjob",
            old_name="description",
            new_name="title",
        ),
        migrations.AddField(
            model_name="importjob",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="accepted",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="validation_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
