# Generated by Django 4.2.7 on 2024-05-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0105_rename_description_importjob_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importjobreport",
            name="total_rows",
        ),
        migrations.RemoveField(
            model_name="importjobreport",
            name="totals",
        ),
        migrations.AddField(
            model_name="importjobreport",
            name="error_rows",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="importjobreport",
            name="new_rows",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="importjobreport",
            name="skipped_rows",
            field=models.IntegerField(null=True),
        ),
    ]
