# Generated by Django 4.2.7 on 2024-05-23 17:20

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


def migrate_related_models_to_dictionary_entry_array_field(apps, schema_editor):
    # Method to migrate the related models for DictionaryEntry model as ArrayField which
    # were previously related with a Many-to-One relationship.
    # Refer to FW-5867 for more details
    dictionary_entry_model = apps.get_model('backend', 'dictionaryentry')
    note_model = apps.get_model('backend', 'note')
    acknowledgement_model = apps.get_model('backend', 'acknowledgement')
    translation_model = apps.get_model('backend', 'translation')
    alt_spellings_model = apps.get_model('backend', 'alternatespelling')
    pronunciation_model = apps.get_model('backend', 'pronunciation')

    for entry in dictionary_entry_model.objects.all():

        # Collecting data
        notes = list(note_model.objects.filter(dictionary_entry=entry).values_list('text', flat=True))
        acknowledgements = list(acknowledgement_model.objects.filter(dictionary_entry=entry).values_list('text', flat=True))
        translations = list(translation_model.objects.filter(dictionary_entry=entry).values_list('text', flat=True))
        alternate_spellings = list(alt_spellings_model.objects.filter(dictionary_entry=entry).values_list('text', flat=True))
        pronunciations = list(pronunciation_model.objects.filter(dictionary_entry=entry).values_list('text', flat=True))

        # Adding data to instance
        entry.notes = notes
        entry.acknowledgements = acknowledgements
        entry.translations = translations
        entry.alternate_spellings = alternate_spellings
        entry.pronunciations = pronunciations

        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0106_remove_importjobreport_total_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="acknowledgements",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="alternate_spellings",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=225),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="notes",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="pronunciations",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=225),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="translations",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=225),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(migrate_related_models_to_dictionary_entry_array_field),
    ]
