# Generated by Django 4.2.7 on 2024-06-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0107_dictionaryentry_acknowledgements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternatespelling",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="alternatespelling",
            name="dictionary_entry",
        ),
        migrations.RemoveField(
            model_name="alternatespelling",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="note",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="note",
            name="dictionary_entry",
        ),
        migrations.RemoveField(
            model_name="note",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="pronunciation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="pronunciation",
            name="dictionary_entry",
        ),
        migrations.RemoveField(
            model_name="pronunciation",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="dictionary_entry",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="last_modified_by",
        ),
        migrations.DeleteModel(
            name="Acknowledgement",
        ),
        migrations.DeleteModel(
            name="AlternateSpelling",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="Pronunciation",
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
    ]
