# Generated by Django 5.0.6 on 2024-06-20 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0108_remove_alternatespelling_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importjobreport",
            old_name="column_headers",
            new_name="accepted_columns",
        ),
        migrations.AddField(
            model_name="importjobreport",
            name="ignored_columns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=225),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
