# Generated by Django 5.0.7 on 2024-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0111_dictionarycleanupjob_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mtdexportformat",
            name="mtd_site_preview_idx",
        ),
        migrations.RenameField(
            model_name="mtdexportformat",
            old_name="latest_export_result",
            new_name="export_result",
        ),
        migrations.RemoveField(
            model_name="mtdexportformat",
            name="is_preview",
        ),
        migrations.AddField(
            model_name="mtdexportformat",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mtdexportformat",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="accepted",
                max_length=9,
            ),
        ),
    ]
