# Generated by Django 5.1.1 on 2024-09-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0112_mtdexportjob_delete_mtdexportformat"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="failed_rows_csv",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_job_failed_rows_csv_set",
                to="backend.file",
            ),
        ),
    ]
