# Generated by Django 5.1.1 on 2024-09-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0113_importjob_failed_rows_csv_alter_importjob_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importjobreport",
            name="skipped_rows",
        ),
    ]
