# Generated by Django 5.1.1 on 2024-10-01 21:56

from django.core.management import call_command
from django.db import migrations

def load_has_app_fixture(apps, schema_editor):
    call_command("loaddata", "appjson-has_app.json", app_label="backend")

class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0114_remove_importjobreport_skipped_rows"),
    ]

    operations = [
        migrations.RunPython(load_has_app_fixture),
    ]
