# Generated by Django 5.1.1 on 2024-10-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0115_auto_20241001_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="import_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.importjob",
            ),
        ),
    ]
