# Generated by Django 5.1.3 on 2024-12-09 20:36

import backend.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0117_file_import_job_imagefile_import_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="introduction",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="introduction_translation",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lyric",
            name="text",
            field=backend.models.base.HTMLSanitizedTextField(),
        ),
        migrations.AlterField(
            model_name="lyric",
            name="translation",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="introduction",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="introduction_translation",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="introduction",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="introduction_translation",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="storypage",
            name="text",
            field=backend.models.base.HTMLSanitizedTextField(),
        ),
        migrations.AlterField(
            model_name="storypage",
            name="translation",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="widgetsettings",
            name="value",
            field=backend.models.base.HTMLSanitizedTextField(blank=True),
        ),
    ]
