# Generated by Django 5.1.1 on 2024-11-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0117_file_import_job_imagefile_import_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.importjob",
            ),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.importjob",
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.importjob",
            ),
        ),
    ]
