# Generated by Django 5.1.1 on 2025-02-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0120_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default=None,
                max_length=9,
                null=True,
            ),
        ),
    ]
