# Generated by Django 5.1.4 on 2025-02-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0121_alter_importjob_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="related_documents",
            field=models.ManyToManyField(blank=True, to="backend.document"),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="related_documents",
            field=models.ManyToManyField(blank=True, to="backend.document"),
        ),
        migrations.AddField(
            model_name="song",
            name="related_documents",
            field=models.ManyToManyField(blank=True, to="backend.document"),
        ),
        migrations.AddField(
            model_name="story",
            name="related_documents",
            field=models.ManyToManyField(blank=True, to="backend.document"),
        ),
        migrations.AddField(
            model_name="storypage",
            name="related_documents",
            field=models.ManyToManyField(blank=True, to="backend.document"),
        ),
    ]
