# Generated by Django 5.1.4 on 2025-02-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0122_character_related_documents_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
    ]
