# Generated by Django 5.1.6 on 2025-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0126_rename_batch_id_dictionaryentry_legacy_batch_filename_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldictionaryentrysystem",
            name="title",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
