# Generated by Django 5.1.6 on 2025-10-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0127_alter_externaldictionaryentrysystem_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjobreport",
            name="update_rows",
            field=models.IntegerField(null=True),
        ),
    ]
