# Generated by Django 5.1.6 on 2026-01-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0129_alter_bulkvisibilityjob_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="export_params",
            field=models.JSONField(default=dict),
        ),
    ]
