# Generated by Django 5.1.14 on 2026-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0130_exportjob_export_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("ready_for_import", "Ready for import"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("ready_for_import", "Ready for import"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
