# Generated by Django 5.1.6 on 2026-03-06 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0130_exportjob_export_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="export_csv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="export_job_export_csv_set",
                to="backend.file",
            ),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="export_params",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
