# Generated by Django 5.1.14 on 2026-04-30 17:42

from django.core.management import call_command
from django.db import migrations
from django.utils import timezone
from django.db.models import Q

def load_all_fixtures(apps, schema_editor):
    # Replacement for fixture loading previously done in 0003 and 0004.
    call_command("loaddata", "appjson-defaults.json", app_label="backend")
    call_command("loaddata", "default_g2p_config.json", app_label="backend")
    call_command("loaddata", "partsOfSpeech_initial.json", app_label="backend")
    call_command("loaddata", "language_families.json", app_label="backend")
    call_command("loaddata", "languages.json", app_label="backend")


def populate_dates(apps, schema_editor):
    # Replacement for populate_dates in 0003 and 0004.
    # Uses apps.get_model instead of python._get_model
    now = timezone.now()

    app_json_model = apps.get_model("backend", "AppJson")
    part_of_speech_model = apps.get_model("backend", "PartOfSpeech")
    language_family_model = apps.get_model("backend", "LanguageFamily")
    language_model = apps.get_model("backend", "Language")

    for model in (app_json_model, part_of_speech_model, language_family_model, language_model):
        qs = model.objects.filter(Q(created=None) | Q(last_modified=None))
        for obj in qs:
            if obj.created is None:
                obj.created = now
            if obj.last_modified is None:
                obj.last_modified = now
            obj.save()


def update_default_site_menu(apps, schema_editor):
    # Update previously done in migration 0093
    AppJson = apps.get_model("backend", "AppJson")

    try:
        appjson = AppJson.objects.get(key="default_site_menu")
    except AppJson.DoesNotExist:
        return

    # Update the json field with the new data
    appjson.json = {
        "kids": {
            "id": "kids",
            "href": "/kids",
            "title": "Kids",
            "transKey": "navigation-kids",
            "itemsData": []
        },
        "about": {
            "id": "about",
            "title": "About",
            "transKey": "navigation-about",
            "itemsData": [{
                "href": "/our-language",
                "title": "Our Language",
                "transKey": "navigation-our-language"
            }, {
                "href": "/our-people",
                "title": "Our People",
                "transKey": "navigation-our-people"
            }]
        },
        "learn": {
            "id": "learn",
            "title": "Learn",
            "transKey": "navigation-learn",
            "itemsData": [{
                "href": "/songs",
                "title": "Songs",
                "transKey": "navigation-songs"
            }, {
                "href": "/stories",
                "title": "Stories",
                "transKey": "navigation-stories"
            }, {
                "href": "/games",
                "title": "Games",
                "transKey": "navigation-games"
            }]
        },
        "resources": {
            "id": "resources",
            "title": "Resources",
            "transKey": "navigation-resources",
            "itemsData": [{
                "href": "/keyboards",
                "title": "Keyboards",
                "transKey": "navigation-keyboards"
            }]
        },
        "dictionary": {
            "id": "dictionary",
            "title": "Dictionary",
            "transKey": "navigation-dictionary",
            "itemsData": [{
                "href": "/words",
                "title": "Words",
                "transKey": "navigation-words"
            }, {
                "href": "/phrases",
                "title": "Phrases",
                "transKey": "navigation-phrases"
            }, {
                "href": "/alphabet",
                "title": "Alphabet",
                "transKey": "navigation-alphabet"
            }, {
                "href": "/categories",
                "title": "Categories",
                "transKey": "navigation-categories"
            }]
        }
    }

    # Save the updated record
    appjson.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0130_exportjob_export_params"),
    ]

    operations = [

        # Replacement for the RunPython steps in migrations 0003, 0004, and 0093.
        migrations.RunPython(load_all_fixtures),
        migrations.RunPython(populate_dates),
        migrations.RunPython(update_default_site_menu),
    ]
