# Generated by Django 5.1.14 on 2026-06-15 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0131_alter_importjob_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImportJobReport",
            new_name="BatchJobReport",
        ),
        migrations.RenameModel(
            old_name="ImportJobReportRow",
            new_name="BatchJobReportRow",
        ),
        migrations.AlterModelOptions(
            name="batchjobreport",
            options={
                "verbose_name": "Batch Job Report",
                "verbose_name_plural": "Batch Job Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="batchjobreportrow",
            options={
                "verbose_name": "Batch Job Report Row",
                "verbose_name_plural": "Batch Job Report Rows",
            },
        ),
    ]
