# Generated by Django 5.1.14 on 2026-06-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0131_alter_importjob_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="row_count",
            field=models.IntegerField(default=0),
        ),
    ]
