# Generated by Django 5.1.14 on 2026-07-17 18:58

import backend.models.media
import backend.models.validators
import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0132_exportjob_row_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="related_video_links",
            field=backend.models.media.VideoLinksArrayField(
                base_field=embed_video.fields.EmbedVideoField(),
                blank=True,
                default=list,
                size=None,
                validators=[backend.models.validators.validate_no_duplicate_urls],
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="related_video_links",
            field=backend.models.media.VideoLinksArrayField(
                base_field=embed_video.fields.EmbedVideoField(),
                blank=True,
                default=list,
                size=None,
                validators=[backend.models.validators.validate_no_duplicate_urls],
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="related_video_links",
            field=backend.models.media.VideoLinksArrayField(
                base_field=embed_video.fields.EmbedVideoField(),
                blank=True,
                default=list,
                size=None,
                validators=[backend.models.validators.validate_no_duplicate_urls],
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="related_video_links",
            field=backend.models.media.VideoLinksArrayField(
                base_field=embed_video.fields.EmbedVideoField(),
                blank=True,
                default=list,
                size=None,
                validators=[backend.models.validators.validate_no_duplicate_urls],
            ),
        ),
        migrations.AlterField(
            model_name="storypage",
            name="related_video_links",
            field=backend.models.media.VideoLinksArrayField(
                base_field=embed_video.fields.EmbedVideoField(),
                blank=True,
                default=list,
                size=None,
                validators=[backend.models.validators.validate_no_duplicate_urls],
            ),
        ),
    ]
