# Generated by Django 5.1.14 on 2026-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0134_alter_person_bio_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjobreport",
            name="warnings",
            field=models.IntegerField(null=True),
        ),
    ]
