# Generated by Django 5.1.14 on 2026-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0134_alter_person_bio_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjobreport",
            name="warning_rows",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("ready_for_confirmation", "Ready for confirmation"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("started", "Started"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("ready_for_confirmation", "Ready for confirmation"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
