# Generated by Django 5.1.14 on 2026-08-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0134_alter_person_bio_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="backend.file"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="backend.file"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="backend.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="backend.videofile",
            ),
        ),
    ]
