# Generated by Django 5.1.14 on 2026-08-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0134_alter_person_bio_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contact_message",
            field=models.TextField(
                blank=True,
                default="Please contact us if you have any suggestions or feedback regarding our language content.",
            ),
        ),
    ]
