# Generated by Django 5.1.14 on 2026-08-25 23:35

import django.core.validators
import django.db.models.functions.text
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0135_importjobreport_warnings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sitepage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                max_length=225,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="unique_site_slug_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitepage",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                models.F("site"),
                name="unique_sitepage_slug_ci",
            ),
        ),
    ]
