# Generated by Django 5.1.14 on 2026-08-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0136_alter_organization_contact_message"),
        ("backend", "0136_alter_sitepage_unique_together_alter_site_slug_and_more"),
    ]

    operations = []
