# Generated by Django 5.1.14 on 2026-09-02 21:37

import backend.permissions.managers
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0137_merge_20260826_1404'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('system_last_modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('started', 'Started'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('ready_for_import', 'Ready for import')], default=None, max_length=32, null=True)),
                ('validation_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('started', 'Started'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('ready_for_import', 'Ready for import')], default=None, max_length=32, null=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.file')),
                ('failed_rows_csv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_job_failed_rows_csv_set', to='backend.file')),
                ('last_modified_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('run_as_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='backend.site')),
                ('system_last_modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update Job',
                'verbose_name_plural': 'Update Jobs',
            },
            bases=(backend.permissions.managers.PermissionFilterMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='update_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.updatejob'),
        ),
        migrations.AddField(
            model_name='file',
            name='update_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.updatejob'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='update_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.updatejob'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='update_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.updatejob'),
        ),
        migrations.CreateModel(
            name='UpdateJobReport',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('system_last_modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('new_rows', models.IntegerField(null=True)),
                ('error_rows', models.IntegerField(null=True)),
                ('updated_rows', models.IntegerField(null=True)),
                ('warnings', models.IntegerField(null=True)),
                ('accepted_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, default=list, size=None)),
                ('ignored_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, default=list, size=None)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='backend.site')),
                ('system_last_modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update Job Report',
                'verbose_name_plural': 'Update Job Reports',
            },
            bases=(backend.permissions.managers.PermissionFilterMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='updatejob',
            name='validation_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.updatejobreport'),
        ),
        migrations.CreateModel(
            name='UpdateJobReportRow',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('system_last_modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('error', 'Error'), ('invalid', 'Invalid'), ('skip', 'Skip'), ('new', 'New'), ('update', 'Update'), ('delete', 'Delete')], max_length=7)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('row_number', models.IntegerField()),
                ('identifier_field', models.CharField(max_length=225)),
                ('identifier_value', models.CharField(max_length=225)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='backend.updatejobreport')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='backend.site')),
                ('system_last_modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update Job Report Row',
                'verbose_name_plural': 'Update Job Report Rows',
            },
            bases=(backend.permissions.managers.PermissionFilterMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
