# Generated by Django 5.1.14 on 2026-09-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0137_merge_20260826_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="backend.file"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="backend.file"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="image",
                to="backend.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="original",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="video",
                to="backend.videofile",
            ),
        ),
    ]
