# Generated by Django 5.1.14 on 2026-09-22 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0139_updatejob_dictionaryentry_update_job_file_update_job_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionaryentry",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.importjob",
            ),
        ),
    ]
