# Generated by Django 5.1.14 on 2026-09-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0140_replace_0003_and_0004_migrations_for_loading_fixtures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionaryentry",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.importjob",
            ),
        ),
    ]
