services:
  rabbit:
    image: rabbitmq:3.11-management-alpine
    hostname: "rabbit"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/fv
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
    ports:
      - "15672:15672"
      - "5672:5672"
  minio:
    image: minio/minio:RELEASE.2023-04-07T05-28-58Z
    hostname: "minio"
    volumes:
      - minio_data:/export
    environment:
      MINIO_ROOT_USER: e806116643d5ea1cff889f16d93a4a44
      MINIO_ROOT_PASSWORD: 1adc661de44da5022326239d150086b4
    ports:
      - "9000:9000"
      - "9001:9001"
    command: "server /export"
  elastic:
    image: elasticsearch:7.17.9
    hostname: "elastic"
    environment:
      "discovery.type": "single-node"
      "xpack.security.enabled": "false"
    ports:
      - "9200:9200"
      - "9300:9300"
  redis:
    image: redis:7.0-alpine
    hostname: "redis"
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  minio_data:
