# Generated by Django 4.1.7 on 2023-03-02 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('disabled', 'DISABLED'), ('enabled', 'ENABLED'), ('new', 'NEW'), ('published', 'PUBLISHED'), ('republish', 'REPUBLISH')], default='new', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('disabled', 'DISABLED'), ('enabled', 'ENABLED'), ('new', 'NEW'), ('published', 'PUBLISHED'), ('republish', 'REPUBLISH')], default='new', max_length=9)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('disabled', 'DISABLED'), ('enabled', 'ENABLED'), ('new', 'NEW'), ('published', 'PUBLISHED'), ('republish', 'REPUBLISH')], default='new', max_length=9)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
        ),
    ]
