# Generated by Django 4.0.10 on 2023-03-09 23:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(choices=[('disabled', 'DISABLED'), ('enabled', 'ENABLED'), ('new', 'NEW'), ('published', 'PUBLISHED'), ('republish', 'REPUBLISH')], default='new', max_length=9),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('disabled', 'DISABLED'), ('enabled', 'ENABLED'), ('new', 'NEW'), ('published', 'PUBLISHED'), ('republish', 'REPUBLISH')], default='new', max_length=9)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.site')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.site')),
                ('words', models.ManyToManyField(related_name='words', to='app.word')),
            ],
        ),
    ]
