# Generated by Django 4.0.10 on 2023-03-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_site_state_word_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='language',
            new_name='site',
        ),
    ]
