import logging

import pytest
from django.core.management import call_command

from backend.models.media import ImageFile
from backend.tests import factories

COMMAND = "delete_orphaned_thumbnail_files"


@pytest.mark.django_db
class TestDeleteOrphanedThumbnailFiles:
    @pytest.fixture(autouse=True)
    def capture_info_logs(self, caplog):
        # the project's log config filters INFO, so caplog needs the level lowering
        caplog.set_level(logging.INFO)

    def setup_method(self):
        self.site = factories.SiteFactory()

    def create_image_file(self, file_name, site=None, width=100, height=100):
        """
        Creates an ImageFile with a set file name and dimensions. Uses a queryset update because
        FileBase.save() refuses edits to files that already exist. The factory image is 100x100,
        which is within every configured thumbnail size.
        """
        site = site or self.site
        image_file = factories.ImageFileFactory.create(site=site)
        ImageFile.objects.filter(id=image_file.id).update(
            content=f"{site.slug}/{file_name}", width=width, height=height
        )
        return image_file

    def create_thumbnail_set(self, stem, site=None):
        """
        Creates a full set of generated thumbnails for one stem, which is what the app strands when
        thumbnails are regenerated. The command only deletes a thumbnail when another size from the
        same set is orphaned alongside it.
        """
        return [
            self.create_image_file(f"{stem}_{size_name}.jpg", site=site)
            for size_name in ["thumbnail", "small", "medium"]
        ]

    @staticmethod
    def assert_caplog_text(caplog):
        assert "Starting to delete orphaned thumbnail files." in caplog.text
        assert "Finished deleting orphaned thumbnail files." in caplog.text

    @staticmethod
    def read_change_log(tmp_path):
        written = list(tmp_path.glob("delete_orphaned_thumbnail_files_log_*.csv"))
        assert len(written) == 1
        return written[0].read_text()

    def test_invalid_output_dir(self, caplog):
        call_command(COMMAND, output_dir="invalid/dir")

        assert (
            "Output directory 'invalid/dir' does not exist or is not writeable."
            in caplog.text
        )
        assert "Starting to delete orphaned thumbnail files." not in caplog.text

    def test_no_orphans(self, tmp_path, caplog):
        factories.ImageFactory.create(site=self.site)

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "Orphaned ImageFile records: 0" in caplog.text
        assert "Change log written to" not in caplog.text
        self.assert_caplog_text(caplog)

    def test_orphaned_thumbnail_set_is_deleted(self, tmp_path, caplog):
        self.create_thumbnail_set("photo")

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "thumbnails generated by the app: 3 (1 sets)" in caplog.text
        assert ImageFile.objects.count() == 0
        assert self.read_change_log(tmp_path).count("deleted") == 3

    def test_partial_set_is_kept(self, tmp_path, caplog):
        """
        Two of the three sizes could be a set that lost one to an earlier failed delete, or
        something else entirely, so only a complete set is deleted.
        """
        self.create_image_file("photo_small.jpg")
        self.create_image_file("photo_medium.jpg")

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "thumbnails generated by the app: 0 (0 sets)" in caplog.text
        assert "named like a thumbnail but not a complete set: 2" in caplog.text
        assert "only 2 of 3 sizes from its set are orphaned and usable" in caplog.text
        assert ImageFile.objects.count() == 2
        assert "needs_review_incomplete_set,kept" in self.read_change_log(tmp_path)

    def test_lone_thumbnail_is_kept(self, tmp_path, caplog):
        """
        A single file named like a thumbnail could be an upload that happens to share the naming,
        so it is kept rather than deleted.
        """
        self.create_image_file("sunset_small.jpg")

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "named like a thumbnail but not a complete set: 1" in caplog.text
        assert "only 1 of 3 sizes from its set are orphaned and usable" in caplog.text
        assert ImageFile.objects.count() == 1
        assert "needs_review_incomplete_set,kept" in self.read_change_log(tmp_path)

    def test_sets_on_different_sites_are_not_treated_as_one_set(self, tmp_path, caplog):
        other_site = factories.SiteFactory()
        self.create_thumbnail_set("photo")
        self.create_image_file("photo_small.jpg", site=other_site)

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "thumbnails generated by the app: 3 (1 sets)" in caplog.text
        assert "named like a thumbnail but not a complete set: 1" in caplog.text
        assert ImageFile.objects.filter(site=other_site).count() == 1

    def test_thumbnails_attached_to_an_image_are_not_deleted(self, tmp_path, caplog):
        """
        ImageFile is referenced by thumbnail, small and medium as well as original, and only
        original carries related_name="image". Without all seven checks this command would delete
        every thumbnail in the database.
        """
        factories.ImageFactory.create(
            site=self.site,
            thumbnail=self.create_image_file("photo_thumbnail.jpg"),
            small=self.create_image_file("photo_small.jpg"),
            medium=self.create_image_file("photo_medium.jpg"),
        )

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "Orphaned ImageFile records: 0" in caplog.text
        assert ImageFile.objects.count() == 4

    def test_thumbnails_attached_to_a_video_are_not_deleted(self, tmp_path, caplog):
        """
        Video thumbnails are ImageFile records too, through Video.thumbnail/small/medium.
        """
        factories.VideoFactory.create(
            site=self.site,
            thumbnail=self.create_image_file("video_thumbnail.jpg"),
            small=self.create_image_file("video_small.jpg"),
            medium=self.create_image_file("video_medium.jpg"),
        )

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "Orphaned ImageFile records: 0" in caplog.text
        assert ImageFile.objects.count() == 3

    def test_uploaded_image_files_are_kept(self, tmp_path, caplog):
        self.create_image_file("community_photo.png")

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "uploaded image files: 1" in caplog.text
        assert ImageFile.objects.count() == 1
        assert "uploaded_image_file,kept" in self.read_change_log(tmp_path)

    def test_wrong_size_for_a_thumbnail_is_kept(self, tmp_path, caplog):
        """
        get_output_dimensions() never scales up, so a generated thumbnail cannot be larger than the
        size it was made for. Anything bigger is kept for review even if the rest of the set is
        there.
        """
        self.create_thumbnail_set("photo")
        self.create_image_file("photo_thumbnail.jpg", width=900, height=900)

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "named like a thumbnail but the wrong size for one: 1" in caplog.text
        assert "is named like a 'thumbnail' thumbnail but is 900x900" in caplog.text
        assert ImageFile.objects.count() == 1
        assert "needs_review_wrong_size,kept" in self.read_change_log(tmp_path)

    def test_missing_dimensions_is_kept(self, tmp_path, caplog):
        self.create_thumbnail_set("photo")
        self.create_image_file("other_thumbnail.jpg", width=None, height=None)
        self.create_image_file("other_small.jpg")
        self.create_image_file("other_medium.jpg")

        call_command(COMMAND, output_dir=str(tmp_path))

        assert "named like a thumbnail but the wrong size for one: 1" in caplog.text
        # the other two sizes of that stem are a partial set once it is held back
        assert ImageFile.objects.count() == 3

    def test_dry_run_deletes_nothing(self, tmp_path, caplog):
        self.create_thumbnail_set("photo")

        call_command(COMMAND, output_dir=str(tmp_path), dry_run=True)

        assert "Dry run mode enabled. No changes will be made." in caplog.text
        assert "thumbnails generated by the app: 3 (1 sets)" in caplog.text
        assert ImageFile.objects.count() == 3
        assert self.read_change_log(tmp_path).count("would delete") == 3

    def test_sites_argument_limits_the_run(self, tmp_path, caplog):
        other_site = factories.SiteFactory()
        self.create_thumbnail_set("photo")
        self.create_thumbnail_set("photo", site=other_site)

        call_command(COMMAND, output_dir=str(tmp_path), site_slugs=self.site.slug)

        assert f"Scope: {self.site.slug}." in caplog.text
        assert "thumbnails generated by the app: 3 (1 sets)" in caplog.text
        assert ImageFile.objects.filter(site=other_site).count() == 3

    def test_change_log_has_no_file_names(self, tmp_path):
        self.create_thumbnail_set("sensitive_name")
        self.create_image_file("another_sensitive_name.png")

        call_command(COMMAND, output_dir=str(tmp_path))

        contents = self.read_change_log(tmp_path)
        assert "sensitive_name" not in contents
        assert (
            "model,id,site,created,size,width,height,group,action,media_model,title"
            in contents
        )

    def test_media_records_are_not_touched(self, tmp_path):
        image = factories.ImageFactory.create(site=self.site)
        self.create_thumbnail_set("photo")

        call_command(COMMAND, output_dir=str(tmp_path))

        image.refresh_from_db()
        assert ImageFile.objects.filter(id=image.original_id).exists()
